In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **Experimentaci√≥n con Algoritmo Jaro Winkler**

In [ ]:
# Python3 implementation of above approach 
from math import floor, ceil 
  
# Function to calculate the 
# Jaro Similarity of two s 
def jaro_distance(s1, s2): 
      
    # If the s are equal 
    if (s1 == s2): 
        return 1.0
  
    # Length of two s 
    len1 = len(s1) 
    len2 = len(s2) 
  
    # Maximum distance upto which matching 
    # is allowed 
    max_dist = floor(max(len1, len2) / 2) - 1
  
    # Count of matches 
    match = 0
  
    # Hash for matches 
    hash_s1 = [0] * len(s1) 
    hash_s2 = [0] * len(s2) 
  
    # Traverse through the first 
    for i in range(len1): 
  
        # Check if there is any matches 
        for j in range(max(0, i - max_dist),  
                       min(len2, i + max_dist + 1)): 
              
            # If there is a match 
            if (s1[i] == s2[j] and hash_s2[j] == 0): 
                hash_s1[i] = 1
                hash_s2[j] = 1
                match += 1
                break
  
    # If there is no match 
    if (match == 0): 
        return 0.0
  
    # Number of transpositions 
    t = 0
    point = 0
  
    # Count number of occurances 
    # where two characters match but 
    # there is a third matched character 
    # in between the indices 
    for i in range(len1): 
        if (hash_s1[i]): 
  
            # Find the next matched character 
            # in second 
            while (hash_s2[point] == 0): 
                point += 1
  
            if (s1[i] != s2[point]): 
                point += 1
                t += 1
    t = t//2
  
    # Return the Jaro Similarity 
    return (match/ len1 + match / len2 + 
            (match - t + 1) / match)/ 3.0
  
# Driver code 
#s1 = ""
#s2 = ""
  
# Prjaro Similarity of two s 
#print(round(jaro_distance(s1, s2),6)) 
  
# This code is contributed by mohit kumar 29

# Lectura de datos (Paper)

In [ ]:
%%capture
!pip install pandas_ods_reader

In [ ]:
import pandas as pd  
Papers = pd.read_csv("/content/drive/MyDrive/RESEARCH/Thesis/Carmen/data/DatasetC.csv", delimiter=",", error_bad_lines=False, encoding='latin1') 
#Papers.head()

In [ ]:
Papers = Papers[['Area','Titulo','Keywords','ABSTRACT']]
Papers

                Area  ...                                           ABSTRACT
0    computer vision  ...  Nowadays, Artificial Neural networks can be tr...
1    computer vision  ...  Attendance marking is a critical and time-cons...
2    computer vision  ...  In e-learning environment, the main function o...
3    computer vision  ...  Image based or live video feed based face reco...
4    computer vision  ...  Automatic medical diagnosis is an emerging cen...
..               ...  ...                                                ...
495    Deep Learning  ...  In this investigation, we apply deep learning ...
496    Deep Learning  ...  Augmented reality aims to mix real-world visua...
497    Deep Learning  ...  In this paper, a deep learning based road traf...
498    Deep Learning  ...  Epilepsy is a neurological condition affecting...
499    Deep Learning  ...  Lack of enough labeled data is a major problem...

[500 rows x 4 columns]

# Lectura de datos (tesis)

In [ ]:

import pandas as pd  
Tesis = pd.read_csv("/content/drive/MyDrive/RESEARCH/Thesis/Carmen/data/TESIS_UNAM.csv", delimiter=",", error_bad_lines=False, encoding='latin1') 
Tesis.head()

   N√Ç¬∞  ...                                              Url
0    1  ...   https://repositorio.unam.edu.pe/handle/UNAM/94
1    2  ...   https://repositorio.unam.edu.pe/handle/UNAM/91
2    3  ...  https://repositorio.unam.edu.pe/handle/UNAM/101
3    4  ...   https://repositorio.unam.edu.pe/handle/UNAM/84
4    5  ...  https://repositorio.unam.edu.pe/handle/UNAM/98

[5 rows x 6 columns]

In [ ]:
df_tesis_titulo = Tesis[['Titulo']]
df_tesis_abstract=Tesis[['abstract']]

df_paper_Area=Papers[['Area']]
df_paper_Titulo=Papers[['Titulo']]
df_paper_Keywords=Papers[['Keywords']]
df_paper_ABSTRACT=Papers[['ABSTRACT']]

In [ ]:
df_tesis_titulo

                                              Titulo
0  Data mining model based on associated factors ...
1  Analysis of predictive models based on compute...
2  Data mining model for predicting cases of anem...
3  Text mining to build a data mining model for j...
4  Application of intelligent algorithms for auto...
5  Optimization of distribution unit routes apply...
6  Prediction Model Of Customers Who Will unscrib...
7  Diagnosis of diabetic retinopathy using classi...
8  Information System for the Control and Documen...
9  Predition of irregular consumiption of drinkki...

# Algoritmo Jaro Winkler

In [ ]:
cadena=[]
for tesis in range(df_tesis_titulo.shape[0]):
  str1, str2="",""
  ts_titulo=str1.join(df_tesis_titulo.iloc[tesis])
  ts_abstract=str2.join(df_tesis_abstract.iloc[tesis])
  txt_research=ts_titulo+" "+ts_abstract
  #print(txt_research)
  #print(ts_abstract)
  for paper in range(df_paper_Area.shape[0]):
    str1,str2,str3,str4="","","",""
    pp_area=str1.join(df_paper_Area.iloc[paper])
    pp_titulo=str2.join(df_paper_Titulo.iloc[paper])
    pp_keywords=str3.join(df_paper_Keywords.iloc[paper])
    pp_abstract=str4.join(df_paper_ABSTRACT.iloc[paper])
    #print(pp_abstract)
    research_area=round(jaro_distance(s1=txt_research, s2=pp_area),6)
    research_titulo=round(jaro_distance(s1=txt_research, s2=pp_titulo),6)
    research_keywords=round(jaro_distance(s1=txt_research, s2=pp_keywords),6)
    research_abstract=round(jaro_distance(s1=txt_research, s2=pp_abstract),6)

    cadena.append(tesis)
    cadena.append(paper)
    cadena.append(research_area)
    cadena.append(research_titulo)
    cadena.append(research_keywords)
    cadena.append(research_abstract)

# Exportar resultados

In [ ]:
import csv
with open('JaroW_Carmen.csv', 'w') as csvfile:
    fieldnames = ['Id_tesis','Id_paper','paper_area','paper_titulo','paper_keywords','paper_abstract']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    word=0
    for i in range(int(len(cadena)/6)):
        Id_tesis=cadena[word]
        Id_paper=cadena[word+1]
        research_area=cadena[word+2]
        research_titulo=cadena[word+3]
        research_keywords=cadena[word+4]
        research_abstract=cadena[word+5]
     
        writer.writerow({'Id_tesis': Id_tesis,
                         'Id_paper':Id_paper,
                         'paper_area':research_area,
                         'paper_titulo':research_titulo,
                         'paper_keywords':research_keywords,
                         'paper_abstract':research_abstract})
        cont=word+5
        word=cont+1

# Visualizacion de resultados

In [ ]:
import pandas as pd  
matrix = pd.read_csv("/content/JaroW_CarmenP.csv", delimiter=",", error_bad_lines=False, encoding='latin1') 
matrix.head(500000)

FileNotFoundError: ignored

In [ ]:
df_campos=matrix[["paper_area","paper_titulo","paper_keywords","paper_abstract"]]
df_id=matrix[["Id_tesis","Id_paper"]]

KeyError: ignored

In [ ]:
df_campos["Jaro_W"] = df_campos.mean(axis=1)
df_campos.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

   paper_area  paper_titulo  paper_keywords  paper_abstract    Jaro_W
0    0.559023      0.505163        0.525723        0.732992  0.580725
1    0.559023      0.537259        0.544832        0.754914  0.599007
2    0.559023      0.542630        0.496368        0.789197  0.596805
3    0.559023      0.489347        0.509653        0.780319  0.584585
4    0.559023      0.501848        0.539498        0.779595  0.594991

In [ ]:
df_merge = pd.concat([df_id, df_campos], axis=1, sort=False)
df_merge

      Id_tesis  Id_paper  paper_area  ...  paper_keywords  paper_abstract    Jaro_W
0            0         0    0.559023  ...        0.525723        0.732992  0.580725
1            0         1    0.559023  ...        0.544832        0.754914  0.599007
2            0         2    0.559023  ...        0.496368        0.789197  0.596805
3            0         3    0.559023  ...        0.509653        0.780319  0.584585
4            0         4    0.559023  ...        0.539498        0.779595  0.594991
...        ...       ...         ...  ...             ...             ...       ...
2495         4       495    0.567678  ...        0.543142        0.727842  0.593672
2496         4       496    0.567678  ...        0.533303        0.644246  0.569665
2497         4       497    0.567678  ...        0.569578        0.707275  0.594840
2498         4       498    0.567678  ...        0.528018        0.649143  0.568973
2499         4       499    0.567678  ...        0.541367        0.736382  0.590648

[2500 rows x 7 columns]

In [ ]:
df_avrg=df_merge[["Id_tesis","Id_paper","Jaro_W"]]
df_avrg

      Id_tesis  Id_paper    Jaro_W
0            0         0  0.580725
1            0         1  0.599007
2            0         2  0.596805
3            0         3  0.584585
4            0         4  0.594991
...        ...       ...       ...
2495         4       495  0.593672
2496         4       496  0.569665
2497         4       497  0.594840
2498         4       498  0.568973
2499         4       499  0.590648

[2500 rows x 3 columns]

In [ ]:
df_avrg.to_csv("JaroW_CarmenP.csv")

In [ ]:
R_df = df_avrg.pivot(index = 'Id_paper', columns ='Id_tesis', values = 'AVRG').fillna(0)
R_df.head(500)

KeyError: ignored

In [ ]:
invoices = pd.DataFrame(R_df,columns = [0,1,2,3,4])
invoices.head(10)

NameError: ignored

In [ ]:
import matplotlib.pyplot as plt
#plotbar=invoices.groupby(['Id_paper',0,1,2,3,4])
#plotbar.plot(kind='bar')
#plt.title('')
#plt.xlabel('Job Offer')
#plt.ylabel('CV Rating')

# Secci√≥n de pruebas

In [ ]:
#Aqui se ingrese el id de tesis que se desea filtrar
Id_tesis_filtro=0
by_year = R_df.sort_values(Id_tesis_filtro,ascending=False)
by_year=by_year.head(5)
by_year

NameError: ignored

In [ ]:
# CONSULTAS DE TESIS / BUSQUEDAS
Id_tesis=0
str1, str2="",""
ts_titulo=str1.join(df_tesis_titulo.iloc[Id_tesis])
ts_abstract=str2.join(df_tesis_abstract.iloc[Id_tesis])
txt_research=ts_titulo+" "+ts_abstract
print("DATOS DEL TESIS / BUSQUEDA")
print(ts_titulo)
print(ts_abstract)
print("\n")
#CONSULTAS DE PAPERS 
Id_paper=310
str1,str2,str3,str4="","","",""
pp_area=str1.join(df_paper_Area.iloc[Id_paper])
pp_titulo=str2.join(df_paper_Titulo.iloc[Id_paper])
pp_keywords=str3.join(df_paper_Keywords.iloc[Id_paper])
pp_abstract=str4.join(df_paper_ABSTRACT.iloc[Id_paper])
print("DATOS DEL PAPER")
print(pp_area)
print(pp_titulo)
print(pp_keywords)
print(pp_abstract)

DATOS DEL TESIS / BUSQUEDA
Data mining model based on associated factors for predicting college dropout.
The following research project aims to develop a data mining model, analyzing the learning paradigm to attack the problem of student desertion presented by universities, mentioning some research that uses different architectures of algorithms in the field of education (Milton, Neto, & Carlos, 2012) as the prediction of courses to choose, academic performance, student classification, among others. The investigation arises when observing a decay in the vegetative growth of the national university of Moquegua, visually it is possible to be observed that the people tend to desert when their average of the semester is very low, for that reason the interest arises to explore the diverse factors that motivates to a person to make that decision and fundamentally take that thought to a machine capable of making the classification to generate the same human activity. the CRISP DM methodology is used to develop the predictive model and a first information gathering approach is carried out to analyze the most important variables for the classification model, afterwards an exploration of the data is made to define the architecture of the model. Finally, the derivatives of the algorithm are evaluated to observe the learning of the machine and to compare the results with new data and to determine the influence of the model with the estimation of desertion.


DATOS DEL PAPER
Data Mining
Analysis models of technical and economic data of mining enterprises based on big data analysis
mining enterprises , technical and economic data , BP neural network , prediction models
Characteristics of the technical and economic data of mining enterprises are multi-dimensionality and nonlinearity. The sales price data of mineral products is an important economic indicator of mining enterprises, and the geological data is an important technical data. The analysis method of the technical and economic data is researched using technologies of big data analysis and data mining. The fluctuation pattern and influencing factors of the mineral products price are analyzed. The prediction model of the mineral products price is established using artificial neural network. The results show that the practicability of the prediction model is strong, and the prediction accuracy is high. During the process of mineral development, due to the limitation of technical conditions and equipment conditions, lots of geological data have been lost, which reduces the accuracy of the orebody shape and that of reserves estimation. Based on techniques of geostatistics and artificial neural network, the prediction model of the geological missing data is established. By using the model, the regularity of geological data of single borehole, the regularity of geological data of group boreholes and the regularity of geological data of all boreholes is discussed and analyzed. It has been proved that most of the geological missing data can be predicted and interpolated, and results of prediction and interpolation are reliable.